Implement mute/unmute room and add offer to join
meetecho/janode pull request #12
Opened 2022-08-03 11:50 UTC by golgetahir

Hi team, thanks for the implementation helped me greatly. Though in the audio bridge plugin, there are some events not there so I added mute/unmute with event callback to peers and generate_offer flag to join room. I am sharing this PR with you hoping that it will be merged or help in any way. Thanks a lot for great work!

2022-08-03 12:36 UTC, atoppi requested changes
Thank for the effort @golgetahir.
I have left some comments that should be addressed before merging the PR.

2022-08-03 12:36 UTC, atoppi commented on src/plugins/audiobridge-plugin.js
> +  ROOM_MUTED: 'audiobridge_room_muted'
As a convention, I'd prefer having `SUCCESS` and `ERROR` as last events, so could you please move `ROOM_MUTED` two positions up ?

2022-08-03 12:36 UTC, atoppi commented on src/plugins/audiobridge-plugin.js
> +            janode_event.data.room = message_data.room;
This is not necessary, the message handler already fills the `room` property before parsing the events

2022-08-03 12:36 UTC, atoppi commented on src/plugins/audiobridge-plugin.js
> +   *
Missing description of the function

2022-08-03 12:36 UTC, atoppi commented on src/plugins/audiobridge-plugin.js
> +   * @returns {} - Returns event as success or error
This should return something like

`Promise<module:audiobridge-plugin~AUDIOBRIDGE_EVENT_MUTE_ROOM_RESPONSE>`

with a simple definition of `AUDIOBRIDGE_EVENT_MUTE_ROOM_RESPONSE` as
```
/**
 * The response event for audiobridge mute request.
 *
 * @typedef {object} AUDIOBRIDGE_EVENT_MUTE_ROOM_RESPONSE
 * @property {number|string} room - The involved room
 */
```

2022-08-03 12:36 UTC, atoppi commented on src/plugins/audiobridge-plugin.js
> +  async join({ room, feed, display, muted, pin, token, quality, volume, record, filename, rtp_participant, group, generate_offer }) {
Missing docs for `generate_offer` parameter

2022-08-03 12:36 UTC, atoppi commented on src/plugins/audiobridge-plugin.js
> +   *
Missing description

2022-08-03 12:36 UTC, atoppi commented on src/plugins/audiobridge-plugin.js
> +   * @returns {} - Returns event as success or error
Similarly to the mute function, this should return a documented

`Promise<module:audiobridge-plugin~AUDIOBRIDGE_EVENT_UNMUTE_ROOM_RESPONSE>`

2022-08-03 12:36 UTC, atoppi commented on src/plugins/audiobridge-plugin.js
> +
Please remove this empty line

2022-08-03 12:36 UTC, atoppi commented on src/plugins/audiobridge-plugin.js
> + * @property {string} EVENT.AUDIOBRIDGE_ROOM_MUTED {@link module:audiobridge-plugin~AUDIOBRIDGE_ROOM_MUTED}
Please keep ERROR as the last event, just move muted one position up

2022-08-03 12:36 UTC, atoppi commented on src/plugins/audiobridge-plugin.js
> +    /**
Please keep ERROR in the last position

2022-08-03 13:53 UTC, golgetahir commented
@atoppi Thanks for the review, I think I have done it accordingly now.

2022-08-03 14:07 UTC, atoppi commented
Thanks looks good now!
I'll merge it once I have the chance to check that everything works as expected.

2022-08-03 14:08 UTC, atoppi approved these changes

2022-08-05 09:13 UTC, atoppi requested changes
Everything seems to work as intended.
I've left some other notes.

The sample code under `examples/audiobridge` is missing.
I will add it once the PR has been merged.

2022-08-05 09:13 UTC, atoppi commented on src/plugins/audiobridge-plugin.js
> +  ERROR: 'audiobridge_error'
missing trailing comma

2022-08-05 09:13 UTC, atoppi commented on src/plugins/audiobridge-plugin.js
> +const REQUEST_UNMUTE_ROOM = 'unmute_room'
missing semicolons for both lines

2022-08-05 09:13 UTC, atoppi commented on src/plugins/audiobridge-plugin.js
> +      return evtdata;
according to janus docs, room is not part of the success response.
Could you please copy the `room` id from the request body? e.g.

```
if (event === PLUGIN_EVENT.SUCCESS) {
      evtdata.room = body.room;
      return evtdata;
}
```

2022-08-05 09:13 UTC, atoppi commented on src/plugins/audiobridge-plugin.js
> +        return evtdata;
same as mute room, please add the missing room attribute

2022-08-09 12:03 UTC, golgetahir commented
Thanks for review, changes are done.

2022-08-09 12:16 UTC, atoppi reviewed
Thanks, it seems you missed some curly brackets

2022-08-09 12:16 UTC, atoppi commented on src/plugins/audiobridge-plugin.js
> +    if (event === PLUGIN_EVENT.SUCCESS)
Missing curly brackets for the if block

2022-08-09 12:16 UTC, atoppi commented on src/plugins/audiobridge-plugin.js
> +      if (event === PLUGIN_EVENT.SUCCESS)
Missing curly brackets for the if block

2022-08-10 08:11 UTC, atoppi approved these changes

2022-08-22 08:41 UTC, merged

2022-08-22 08:53 UTC, atoppi commented
fyi in https://github.com/meetecho/janode/commit/903cd75b285ef160e646bba1138ddbdc5c611437 I have also added the sample code for this feature and corrected some indentation issues.
Thanks again!